### ISSUE TITLE
Can I use this plugin to run code remotely?

### ISSUE THREAD

**Issue by ddebby** [allegroai/clearml-pycharm-plugin#4]
Can this plugin work with clearml-session to debug remotely? I can not find any documents about this.

**Comment by bmartinn** [comment]
Hi @ddebby 
> Can this plugin work with clearml-session to debug remotely?

Yes :)

> I can not find any documents about this.

https://clear.ml/docs/latest/docs/guides/ide/integration_pycharm/
https://clear.ml/docs/latest/docs/apps/clearml_session#how-it-works

Long story short, `clearml-session` will open a direct SSH connection into the remote container.
This means that if you do:
```
ssh root@localhost -p 8022
```
You are actually connecting into the remote machine.

In your PyCharm, configure the remote interpreter to `localhost` with port `8022` and use the password the `clearml-session` outputs for you (something like `c5d19b3c0fa9784ba4f6aeb568c1e036a4fc2a4bc7f9bfc54a2c198d64ceb9c8`)
See detailed instruction [here](https://www.jetbrains.com/help/pycharm/configuring-remote-interpreters-via-ssh.html#ssh-configurations)

**Comment by qwaxys** [comment]
@ddebby Closing this issue for now, if you have any more questions feel free make a new issue and if related, mention this thread.

**Comment by qwaxys** [comment]
@ddebby Closing this issue for now, if you have any more questions feel free make a new issue and if related, mention this thread.
